volumes:
  data_db:

services:
  postgres:
    image: postgres:15.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=tester
      - POSTGRES_PASSWORD=246357
      - POSTGRES_DB=mfv-challenge
    healthcheck:
        test: pg_isready -U mydbuser -d mydbname
        interval: 30s
        timeout: 10s
        retries: 5
  migrate:
    image: migrate/migrate
    volumes:
        - ./migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://tester:246357@postgres:5432/mfv-challenge?sslmode=disable", "up", "3"]
    depends_on:
      - postgres
    links:
      - postgres
    restart: on-failure
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - DB_HOST=postgres
      - SERVER_HOST=0.0.0.0
    depends_on:
      - postgres
    restart: on-failure
    command: [ "/app/main" ]