server:
  host: localhost
  port: 8080

db:
  host: localhost
  port: 5432
  database: mfv-challenge
  user: tester
  password: 246357

auth:
  secret: 432hjsa92l
  duration: 60m
  enabled: true
  whitelist:
  - /api/login